name: storsys
description: "A Flutter inventory management app using Appwrite and GetX."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  appwrite: ^15.0.0
  get_storage: ^2.1.1
  image_picker: ^1.0.7
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dependency_overrides:
  flutter_web_auth_2: ^4.0.0

